# See https://github.com/DavidAnson/markdownlint-cli2
---
config:
  MD013:
    # https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
    line_length: 120
  MD033: false  # Allow inline HTML (useful for comments)
  MD041: false  # First line doesn't need to be top level heading

# Ignore files referenced by .gitignore (only valid at root)
gitignore: true
