---
repos:
  # generic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: forbid-submodules

  # Markdown linter
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  # YAML linter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  # pyproject.toml formatter
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.17
    hooks:
      # Update the uv lockfile
      - id: uv-sync

  # Ruff linter/formatter for Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  # Astral Ty type checker (tech preview)
  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check .
        language: system
        files: \.py$

  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
