---
extends: default

# ref: https://yamllint.readthedocs.io/en/stable/rules.html
rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    level: warning
  truthy:
    allowed-values: ['true', 'false']
